### ISSUE TITLE
UDP support

### ISSUE THREAD

**Issue by czechboy0** [IBM-Swift/BlueSocket#1]
UDP support would be great for streaming of data like sound and video.

**Comment by nicholasjackson** [comment]
I have been looking into the UDP support as I would like to build a StatsD client for swift and from looking at the documentation on sending datagrams with LibC this does not look massively complicated.

My main concern is how to test the code other than some adhoc manual tests, again I am happy to implement some unit tests but this would require some reasonably structural changes to the Socket class to implement an abstraction for libc sockets and inject this as a dependancy into the Socket class.

If this is not already on your roadmap and if I took this work on would you be interested in receiving a pull request and also helping out with some questions I may have.  I was thinking about tackling the problem this weekend.

**Comment by billabt** [comment]
UDP support is coming. Some of the infrastructure is already there. It's definitely in plan.  if you'd like to take a stab at it, I'd be happy to answer any questions you might have.

**Comment by nicholasjackson** [comment]
Thanks Bill I will have a go this weekend.

**Comment by billabt** [comment]
Sounds good. I added more scaffolding this morning. Also, there's a new delegate model in the works so it might be helpful to keep that in the back of your head. Have a happy coding weekend.

**Comment by kweinmeister** [comment]
Excellent, @nicholasjackson. I have uploaded the pull request template, which links to our CLA, to save time when we're ready for that.

**Comment by nicholasjackson** [comment]
Bit late to this but i started merging my UDP code into BlueSocket yesterday, hopefully it will be finished and a pull request on the way soon.

**Comment by billabt** [comment]
Sounds good to me. Thanks.

**Comment by nicholasjackson** [comment]
Hey @billabt made some good progress today, I am just refactoring a little to make my life easier.  To keep things consistent with UDP I was thinking that the connect method would only store the signature UDP being fire and forget and create the outbound socket on socket.write not actually open a socket like a TCP socket.

At present I am only making UDP sockets one way, i.e I am not creating a reading socket for every writing socket to try and facilitate two way communication like TCP.  I think if you do want to do two way communication with UDP then you should explicitly create a reading socket and a writing socket.

Kind regards,

Nic

**Comment by billabt** [comment]
Hi @nicholasjackson, are you still working on UDP support?  Haven't heard from you in awhile...  Hope all is well - Bill

**Comment by billabt** [comment]
Hi @nicholasjackson, are you still planning on submitting a PR with UDP support?  If, we're probably going to go ahead and implement it...  Thanks.

**Comment by nicholasjackson** [comment]
@billabt Yes sorry, I have pretty much finished this, just been caught up at work.

**Comment by billabt** [comment]
Ok, cool. Thanks.

**Comment by nicholasjackson** [comment]
@billabt i have the tests passing, im not so happy with the implementation due to the differences with udp and tcp but have tried to create a unified interface, will push to my branch this morning if you could review and then maybe we can look at a way of doing a 2.0 release which introduces breaking api changes for a more logical interface?

**Comment by billabt** [comment]
Ok, let me know when you've pushed it and I'll take a look.  I'll be interested in what you think would be a more *logical* interface...  Thanks.

**Comment by Jumhyn** [comment]
@billabt I've been toying with adding UDP support as well, was wondering if you had any further thoughts or guidance since this discussion. Otherwise, will update you when I have pushed to my branch.

**Comment by Jumhyn** [comment]
In particular, would love to know if you have thoughts about the API for `read(into:from:)`. The signature of recvfrom translates most directly to an `inout Address` parameter, but this isn't very Swifty, IMO. Could also return a tuple of `(Int, Address)`, or drop `read(into:bufSize:from:)` to keep only methods where the data argument has embedded information about size (i.e. `NSMutableData`/ `Data`)

**Comment by billabt** [comment]
I'd probably build a basic function much like I did for TCP's `read(into: bufSize)` and then build out some convenience functions around it like the TCP functions `readString()` and `read(into:)` where the resultant size being returned is not necessary.

**Comment by nicholasjackson** [comment]
Hey @billabt my branch is now complete, keeping interface compatbility was akward due to differences with TCP and UDP for example in the listen phase in UDP which does not exist.  To get around this I have implemented the UDP read into the block acceptClientConnection phase with read just returning the buffer.  This does not allow for the return of the connecting address which is allowed with UDP connections in order to send a reply.  If you could take a look please as I suggest we have to introduce a breaking interface change in the next version to get a better implementation.

**Comment by Jumhyn** [comment]
@nicholasjackson Have you pushed? I've had some thoughts about the interface as well and would be interested in seeing what you've come up with, but I don't see the changes on your fork.

**Comment by billabt** [comment]
Neither do I...

Seems to me that only interface change that's needed is relatively simple.  The two `read` APIs should return a tuple, containing number of bytes read and the address they were read from...

Am I missing something?

**Comment by billabt** [comment]
I've added the following stubs to BlueSocket...  Any comments appreciated...
For listening
```
	public func listen(forMessage buffer: UnsafeMutablePointer<CChar>, bufSize: Int, on port: Int, maxBacklogSize: Int = Socket.SOCKET_DEFAULT_MAX_BACKLOG) throws -> (bytesRead: Int32, address: Address?)
	public func listen(forMessage data: NSMutableData, on port: Int, maxBacklogSize: Int = Socket.SOCKET_DEFAULT_MAX_BACKLOG) throws -> (bytesRead: Int32, address: Address?)
	public func listen(forMessage data: inout Data, on port: Int, maxBacklogSize: Int = Socket.SOCKET_DEFAULT_MAX_BACKLOG) throws -> (bytesRead: Int32, address: Address?)
```
For reading
```
	public func read(into buffer: UnsafeMutablePointer<CChar>, bufSize: Int, from address: Address) throws -> (bytesRead: Int, address: Address?)
	public func read(into data: NSMutableData, from address: Address) throws -> (bytesRead: Int, address: Address?)
	public func read(into data: inout Data, from address: Address) throws -> (bytesRead: Int, address: Address?)
```
For writing
```
	public func write(from buffer: UnsafeRawPointer, bufSize: Int, to addresss: Address) throws
	public func write(from data: NSData, to addresss: Address) throws	
	public func write(from data: Data, to addresss: Address) throws
```
I believe that these will cover most if not all of the UDP cases...  The other APIs are connection-based and not applicable to UDP.  Finally, since all these APIs are *NEW*, there will be **NO** source breaking changes since the existing API does not change.

Any comments appreciated.

**Comment by Jumhyn** [comment]
That looks like about what I was thinking. However, for the `read` calls, we don't need the input `Address`. Since `recvfrom` accepts data from all addresses and simply returns the address in the `struct sockaddr *` provided, the input value is ignored. Without this parameter, however, the UDP and TCP calls become ambiguous. I have submitted a pull request with a proposed fix (namely, rename `read` to `readDatagram` for UDP calls). Let me know if you think there is a better solution.

**Comment by Jumhyn** [comment]
It should probably also be considered whether we want the possibility of any kind of general interface across UDP/TCP. As it stands, entirely separate methods must be used between the two, whereas calls to the C API are basically agnostic once you have done the appropriate setup (via `listen`/`connect`, etc.).

**Comment by billabt** [comment]
This is true, but unfortunately, it's not as clear exactly what you're doing...  With this API, it's very, very hard to confuse matters.

**Comment by billabt** [comment]
Here's the alternative I came up with for `read`.
```
	public func read(into buffer: UnsafeMutablePointer<CChar>, bufSize: Int, from address: inout Address) throws -> Int
	public func read(into data: NSMutableData, from address: inout Address) throws -> Int
	public func read(into data: inout Data, from address: inout Address) throws -> Int
```
This resolves the ambiguity...

**Comment by Jumhyn** [comment]
Fair point. The only issue I see with an `inout Address` parameter is that it requires the creation of a 'dummy' address preceding the call:

```
var address = Address.ipv4(sockaddr_in()) // unused!
read(into: data, from: address)
```

since Swift doesn't allow you to pass parameters (even `inout` parameters) before initialization.

 I would also say that the above solution is less clear. We aren't really reading 'from' the address labeled `from`. Instead `address` is acting purely as a return value. That sort of fake multiple return makes sense in C, but is really better modeled by a tuple return in Swift.

**Comment by billabt** [comment]
You're right, let me stew on it overnight...  Unfortunately, I've already checked it in. 😝  But, it doesn't break anything.  We may end up back at your original PR and `readDatagram`, after all, we already have a `readString`... 😃

**Comment by Jumhyn** [comment]
Ok! I'll resubmit the PR when I have the chance, feel free to sleep on it to see if you can come up with anything better :)

**Comment by billabt** [comment]
Don't worry about the PR, I had edited my comment.  I guess you didn't see the change.  We'll go with `readDatagram`...  I just checked in the changes.

**Comment by Jumhyn** [comment]
Whoops, didn't see the edit. Sounds good!

**Comment by billabt** [comment]
@Jumhyn:  Do you want to take a crack at creating an easy way to create and `Address`?

**Comment by billabt** [comment]
Oops, didn't see you already did it in the PR.  Great!!!

**Comment by Jumhyn** [comment]
Haha yep! Ran into the same issue while writing the UDP test 😃

**Comment by billabt** [comment]
I'm not sure why things built for you or why CI built as well...  Strange.  Had to make changes, moved your helper method to the `Socket` class level along with other utility type methods.

**Comment by Jumhyn** [comment]
Hmm interesting... I'm not building on Linux, so that might be the issue?

**Comment by Jumhyn** [comment]
It also strikes me that implementing a subclass such as `UDPSocket` might result in a simpler interface, though not sure if you'd want to head in that direction.

**Comment by billabt** [comment]
Yeah, I figured you weren't building on Linux...  That's a requirement.  I've noticed couple of things in your latest PR that won't pass Linux muster.  I'll go over your PR in detail tomorrow.  As far as a subclass for `Socket` to be `UDPSocket`, you're right, I don't want to head in that direction. 😝  Because this is used by **Kitura** and a few other things around here, I can't afford to take chances.

**Comment by Jumhyn** [comment]
Great, thanks! I'll look into getting a Linux build environment set up.

**Comment by billabt** [comment]
As far as why I've kept functions at the class level rather than adding them elsewhere, I find it much easier to deal with these types of functions at the highest class level.  Two reasons, it hides the implementation of the lower levels and makes it easier and less error prone to code.

**Comment by Jumhyn** [comment]
Alright that makes sense. I've set up my Linux environment and have the tests passing there, just FYI when you have a chance to look again.

**Comment by billabt** [comment]
UDP is now supported in version 0.12.12.  Many thanks to @Jumhyn for the assistance in making this happen.
