### ISSUE TITLE
Unable to Connect to UDP Port

### ISSUE THREAD

**Issue by dirk68-fu** [IBM-Swift/BlueSocket#101]
Hi,

I am trying to connect via UDP to a port on another computer or even localhost. Unfortunately I was not able to get it working. This is what I have (please excuse the !s in this test code):

```swift
 let socket = try! Socket.create(family: .inet, type: .datagram, proto: .udp)
  try! socket.connect(to: "127.0.0.1", port: 1234, timeout: 5000)
```
on the other end _nc_ is listening like that:
` nc -u -l 1234`

I always get `SOCKET_ERR_GETADDRINFO_FAILED`

what am I doing wrong?

(Using xCode on macOS.)

**Comment by billabt** [comment]
Take a look at the _testReadWriteUDP_ function in SocketTests.swift...  You have to remember that _UDP_ is a **connectionless** protocol.  You don't need to connect prior to write and reading from a UDP socket.  The test function that I referenced above should point you in the right direction.  Compare it with the _testReadWrite_ function which does the _exact same thing_ as the other function only using _TCP_ instead of _UDP_.  When you compare them, you'll be able to see the differences in the protocol.  Re-open the issue if you have anymore questions.

**Comment by dirk68-fu** [comment]
[facepalm] How stupid of me. ;-)
Could the error message be improved, in case someone else has the same problem or is that more trouble than it is worth?

**Comment by billabt** [comment]
I could throw an exception if you call connect on a UDP Socket just in case someone tries it again. 😉
