### ISSUE TITLE
connect not using right family when resolving Hostname

### ISSUE THREAD

**Issue by lucJW** [IBM-Swift/BlueSocket#128]
Hi,

I've two iOS devices which are communicating via BlueSocket. The client is finding the server via Bonjour and thus uses the hostname of the server to connect to it (something like "yourIpad.local."). If the devices are on a "normal" WiFi, everything works. The sockets are created with
`Socket.create(family: .inet, type: .stream, proto: .tcp)`

If I now enable the personal hotspot on one device and join this WiFi with the other device, the client has troubles connecting to the server. I traced it down to the following:

The `connect(to host: String, port: Int32, timeout: UInt = 0)` method is looking up the hostname via: `getaddrinfo(host, String(port), &hints, &targetInfo)`
After that, it iterates through the addresses and tries to connect. For some reason, when using the personal hotspot, the first addrInfo from the OS is an IPv6 entry ( info!.pointee.ai_family == 30). The client tries to connect to the IPv6 address which results in a timeout since the server is only listening for IPv4. After the timeout, it uses the second addrInfo record (it's a while loop) and can connect to the server.

From my point of view, the "hints" variable for the getaddrinfo-call needs to specify the family of the socket to pass it to the getaddrinfo call - currently it passes "AF_UNSPEC" as ai_family parameter.
If I change the hint-variable to

```
			var hints = addrinfo(
				ai_flags: AI_PASSIVE,
				ai_family: signature?.protocolFamily.value ?? AF_UNSPEC,
				ai_socktype: socketType.value,
				ai_protocol: 0,
				ai_addrlen: 0,
				ai_canonname: nil,
				ai_addr: nil,
				ai_next: nil)
```

Everything works as expected.

What do you think of it?

**Comment by billabt** [comment]
You're right.  I've incorporated the change into _version 1.0.1_.  Thanks.

**Comment by billabt** [comment]
After doing some further research, the original behavior is correct.  However, there are cases, such as yours where this behavior is not desirable.  To accommodate that, I've added an additional parameter to the _connect()_ signature that when set to _true_ allows you to override the default behavior and restrict the connection to a socket of the same family.  This means that you'll have to make a slight change to your code to get the behavior you desire.

Change this:
```
try connect(to: myHost, port: myPort, timeout: 0)
```
to this:
```
try connect(to: myHost, port: myPort, timeout: 0, familyOnly: true)
```

This will take effect with the latest (_1.0.2_) version of _BlueSocket_.

**Comment by lucJW** [comment]
Thanks for the changes. Could you explain, why the original behaviour is correct?

**Comment by billabt** [comment]
The original behavior is to allow for seamless connections in the event that the host changes from IPV4 to IPV6.  By changing it to what we originally changed it to, we lost that functionality.  I ran a number of tests on my test machine here on both macOS and Linux and both failed with the change in place.

I believe the problem you're running into is because the hotspot connection _only supports IPV6_,  This is a _reported Apple bug_ that Apple claims won't be fixed.

**Comment by lucJW** [comment]
> I believe the problem you're running into is because the hotspot connection only supports IPV6, This is a reported Apple bug that Apple claims won't be fixed.

But my socket is only listening on IPv4 and the connection is done via IPv4.

Why do I need to specify the protocol family in the constructor when the socket does not respect this setting? 
Should we maybe adjust the constructor parameter to say something like "IPv4", "IPv6" and "don't care" !?

**Comment by billabt** [comment]
You're correct, however when going thru hotspot, the **default** is IPV6.  There is **NO** IPV4 address available however, IPV6 will allow a pass through to IPV4 _if and only_ you specify it.

For example, suppose you have client using IPV4 and a server using IPV4.  Everything works just fine.  However, if the server upgrades to use IPV6, leaving the code as it was before the changes I just made will result in a connection failure because IPV4 is not explicitly specified.  This is _NOT_ the desirable behavior.  The way the code works now, the connection will be successful.

With the changes I made to support your case as well as the desirable case, you're not actually specifying the protocol family.  You're really saying, "only connect me to a socket that's in the same family as me".

Hope this makes sense to you. If you can find documentation that'll convince me otherwise, I'd be more than happy to reconsider making additional changes (or simply flipping the default if that's all it takes).  Specifying the family in the connect call is, IMHO, confusing.  Right now, it's either use the client socket's family to get the server address or don't.

**Comment by lucJW** [comment]
Thanks for your explanations. After googeling a bit, I found that there some dual-stack implementations on the different operating systems - that was new to me. 
But at the end I'm again wondering why I have to specify a Protocol-Family when I **create** a socket and this protocol is not respected when connecting (or listening).

I read about the Windows and Linux IPv4/IPv6 Dualstack implementations that you can specify to listen to IPv4 only, IPv6 only or both (when using the wildcard address).
Is BlueSocket supporting the case that you listen to both IPv4 and IPv6 with one socket?
If so, I'm again at the point: why not specify exactly this when **creating** the socket (IPv4 only, IPv6 only or both)? And then strictly stick to this setting.

Am I missing something? (beside the fact, that depending on the implementation, this could introduce some breaking changes)

**Comment by lucJW** [comment]
@billabt what do you think of my suggestions above?

**Comment by billabt** [comment]
First, the breaking changes that would need to be introduced are, at this point in time, not acceptable.  Second, the changes you suggest are, IMHO, confusing.  The current **default** is the _normal, expected_ behavior.  The case you're describing and experiencing is, IMHO, an **edge** case.  In most circumstances, taking advantage of the dual stack implementation is what is desired.
