### ISSUE TITLE
UDP Wifi Vs Carrier Network Behavior

### ISSUE THREAD

**Issue by pjlamber** [IBM-Swift/BlueSocket#159]
I'm trying to send UDP datagrams to a server. UDP is connectionless and so I should be able to just create the socket and send the datagram:

socket = try Socket.create(family: .inet, type: .datagram, proto: .udp);
try self.socket?.write(from: "Hello", to: Socket.createAddress(for: "xxx.xxx.xxx.xxxx", on: 1234)!)

The code works perfectly fine if my iOS device is on Wifi but if I switch back to my carrier network (T-Mobile), I get the following error code:

Error code: -9980(0x-26FC), Operation not permitted

If I add the connect command, which should not be necessary, it works perfectly fine (on both networks).

socket = try Socket.create(family: .inet, type: .datagram, proto: .udp);
try self.mVideoSocket?.connect(to: "xxx.xxx.xxx.xxxx", port: 1234)
try self.mVideoSocket?.write(from: "Hello")

**Comment by pjlamber** [comment]
Thanks. I think I figured it out. What I noticed is that when I connect to my Wifi and I call Socket.createAddress(...), the family property of the object returned is 'inet' (ipv4). When I toggle back to my carrier network, same property's value is 'inet6' (ipv6). So the assumption is T-Mobile is using ipv6. However, i'm using 'try Socket.create(family: .inet, type: .datagram, proto: .udp)' to create the socket. If I change the family parameter to inet6, it works. 

My solution is to create the address object first, inspect the family property and if it == .inet then use .inet to create the socket, else use .inet6 to create the socket.

**Comment by billabt** [comment]
Ok. That makes sense. I’ll close this for now and you can re-open if necessary. Thanks.

**Comment by billabt** [comment]
I ran a test here doing the same thing and sure enough got the same results as you.  I'm thinking that most carriers now are using **IPV6** as their _default_ now.  I know that any of the stuff I've worked on lately (not Open Source) that potentially uses _Wi-Fi_ always uses **IPV6** for just that reason.  I must've been on Christmas overload 🤪 yesterday when I looked at your note or I would've realized what the problem was sooner and saved you some time.  I think I'm going to add a **note** in the _README_ that talks a bit about that.  I'll also look at seeing if I can catch that and _throw an appropriate exception_.  Thanks.
