### ISSUE TITLE
Performance issues

### ISSUE THREAD

**Issue by lgaches** [IBM-Swift/BlueSocket#53]
I've tried to use BlueSocket in [MongoKitten](https://github.com/lgaches/MongoKitten) which is a swift driver for MongoDB. 

After replacing Vapor Socket by BlueSocket, I ran some performance tests. The results showed an important difference between the two implementations on MacOS and a huge one on Linux.

To run the test you can clone this [repo](https://github.com/OpenKitten/Statistics). Master branch uses the Vapor Socket and bluesocket branch uses the BlueSocket.

The bluesocket code is all  in the [Socket.swift](https://github.com/lgaches/MongoKitten/blob/mk31-BlueSSL/Sources/MongoSocket/Socket.swift) file. Maybe I did something wrong in my implementation ?

### Tests Results
All Tests are done in Release mode.

Here the results from performance tests on Linux :

*Linux 16.04 - 4.4.0-59-generic*
*Intel(R) Xeon(R) CPU E3-1245 V2 @ 3.40GHz - 32GiB*
*Swift version 3.0.2 (swift-3.0.2-RELEASE)*

**BlueSocket**

- Max : 5.32257395982742
- Min : 3.25634396076202
- Average : 3.61253277897835
- Median : 3.46378147602081
- Execution Time : 361.478877007961
- Rounds : 100

**VaporSocket**

- Max : 0.695515990257263
- Min : 0.433806002140045
- Average : 0.532387097477913
- Median : 0.514575988054276
- Execution Time : 53.2749119997025
- Rounds : 100

And on MacOS:
Darwin Kernel Version 16.4.0
Apple Swift version 3.0.2 (swiftlang-800.0.63 clang-800.0.42.1)

swift build -c release
.build/release/SwiftPerformance

- Max : 0.963047981262207
- Min : 0.830860018730164
- Average : 0.873546527028084
- Median : 0.872366487979889
- Execution Time : 87.3994210362434
- Rounds : 100

**VaporSocket**

- Max : 0.877934038639069
- Min : 0.666562974452972
- Average : 0.719885479807854
- Median : 0.714864492416382
- Execution Time : 72.033077955246
- Rounds : 100

**Comment by billabt** [comment]
Try running the same tests after changing the **BlueSocket** *readBufferSize* variable from the default, Socket.DEFAULT_READ_BUFFER_SIZE which is 4096, to 65507, the size that Vapor uses for it's internal buffer.  This can be done simply as illustrated below:
```
let mySocket = Socket.create()
mySocket.readBufferSize = 65507
```
You'll want to change the buffer size *prior* to using the socket.  The default read buffer size for *BlueSocket* defaults to a relatively small size but can be configured on a per application basis unlike Vapor where it's a *let* constant.  This allows it to be tuned to suit the needs of the application.  I probably should add documentation regarding this.

**Comment by lgaches** [comment]
Thanks @billabt. I check that.

**Comment by lgaches** [comment]
After adding `socket.readBufferSize = 65507`, I've pretty much the same result. No improvements.

**Comment by billabt** [comment]
That's interesting. When I ran it here, I saw numbers slightly better than Vapor on Linux (about 5% better) and an almost a 20% improvement on macOS.

**Comment by billabt** [comment]
@lgaches: Maybe it has to do with how you set up the database...  Can you post exactly how you set up the db so that I can follow the exact same steps you did?  Thanks.

**Comment by michel-moreau** [comment]
I tried on my mac and found pretty much the same results as @lgaches 

Darwin Kernel Version 16.0.0
Apple Swift version 3.0.2 (swiftlang-800.0.63 clang-800.0.42.1)

**VaporSocket**
Max : 1.69017899036407
Min : 0.931960999965668
Average : 1.07207236051559
Median : 1.0662505030632
Execution Time : 107.583873033524
Rounds : 100

**BlueSocket** (readbuffersize set to 65507)
Max : 1.85664600133896
Min : 1.13858097791672
Average : 1.25306052803993
Median : 1.22975048422813
Execution Time : 125.413398981094
Rounds : 100

**Comment by billabt** [comment]
I had something not quite set up right here so I started over. 🤔  I was actually getting an error underneath the covers but it wasn't bubbling up.  So my initial results were skewed, it wasn't doing what is was supposed to. (That's what I get for working on Saturday 😃.)  I seem to have it working now and one thing I did notice was that in order for me to get your test program to run here, I had to comment out the `socket.close()` in your version of MongoSocket otherwise, I got the following:
```
13:01:55 [Fatal] The MongoKitten background loop encountered an error and has stopped: Error code: -9982(0x-26FE), Bad file descriptor    [Main:Convenience.swift:fatal] org.openkitten.mongokitten
13:01:55 [Fatal] Please file a report on https://github.com/openkitten/mongokitten    [Main:Convenience.swift:fatal] org.openkitten.mongokitten
```
This error was a result of attempting to read a socket that was closed.  Upon further investigation, I found a minor bug in Socket that was causing this behavior.  I'll check in the fix for it.

In the meantime, I'm going to look more deeply for the performance issues you've raised.

**Comment by billabt** [comment]
The more I dig deeper into this the more I'm inclined to believe that the overall performance issue appears to be as a result of MongoKitten having been originally designed to use *Vapor* sockets.  This is evidenced by the usage of `[UInt8]` arrays for socket I/O.  When you converted it to use *BlueSocket*, you ended up doing a lot of conversions between `[UInt8]` and `Data` since *BlueSocket* primarily uses `Data` for socket I/O.  These conversions turn out to be very expensive. To prove this (primarily to myself 😃), I made changes to *Connection.swift*, *MongoTCP.swif* and *Socket.swift* to test my theory.  Sure enough the performance numbers improved.  Quite dramatically on Linux I might add.

Here are the changes:
**Connection.swift**
Added at the top of `class Connection` under `host`.
```
	var incomingBuffer = [UInt8]()
```
Then down a bit...
```
    private func receive(bufferSize: Int = 1024) throws {
        // TODO: Respect bufferSize
	try client.receive(into: &incomingBuffer)  <------ Added this line.
        buffer.data += incomingBuffer
        
        while buffer.data.count >= 36 {
            let length = Int(buffer.data[0...3].makeInt32())
            
            guard length <= buffer.data.count else {
                // Ignore: Wait for more data
                return
            }
            
            let responseData = buffer.data[0..<length]*
            let responseId = buffer.data[8...11].makeInt32()
            let reply = try Message.makeReply(from: responseData)
            
            if let closure = waitingForResponses[responseId] {
                closure(reply)
                waitingForResponses[responseId] = nil
            } else {
                
            }
            
            buffer.data.removeSubrange(0..<length)
        }
    }
```
In **MongTCP.swift**:
Changed the `receive` function in the `protocol MongoTCP` to this:
```
    /// Receives any available data from the socket
	func receive( into buffer: inout [UInt8]) throws
```
Finally, in **Socket.swift**:
```
public final class MongoSocket: MongoTCP {

    private let socket: Socket

    private var sslEnabled = false
	
	private var data: Data = Data(capacity: 2048) <---- Added this

    public init(address hostname: String, port: UInt16, options: [String: Any]) throws {

        self.sslEnabled = options["sslEnabled"] as? Bool ?? false
        socket = try Socket.create() // tcp socket
	socket.readBufferSize = 1024  <---- Added this, reducing the read buffer size
        if sslEnabled {
            let invalidCertificateAllowed = options["invalidCertificateAllowed"] as? Bool ?? false
            let sslConfig = SSLService.Configuration(withCACertificateFilePath: nil, usingCertificateFile: nil, withKeyFile: nil, usingSelfSignedCerts: invalidCertificateAllowed, cipherSuite: nil)
            socket.delegate = try SSLService(usingConfiguration: sslConfig)
        }
        try socket.connect(to: hostname, port: Int32(port))
    }

    /// Sends the data to the other side of the connection
    public func send(data binary: [UInt8]) throws {
        try socket.write(from: UnsafeRawPointer(binary), bufSize: binary.count)
    }

    /// Receives any available data from the socket  <---- Rewrote this function.
    public func receive( into buffer: inout [UInt8]) throws {
		self.data.count = 0
		buffer.removeAll()
                 _ = try socket.read(into: &self.data)
		return buffer.append(contentsOf: self.data)
    }

    /// `true` when connected, `false` otherwise
    public var isConnected: Bool {
        return socket.isConnected
    }

    /// Closes the connection
    public func close() throws {
        socket.close()
    }
}
```
This yields the following results on macOS (Darwin Kernel 16.5.0) with **BlueSocket**:
```
Max : 0.850748980045319
Min : 0.716965990066528
Average : 0.78427298784256
Median : 0.816421482563019
Execution Time : 79.76615700721741
Rounds : 100
```
And on Linux (Ubuntu 16.04, VMware Fusion VM with 4 cores and 32 GB), we get this:
```
Max : 0.98575201034546
Min : 0.710196018218994
Average : 0.875569160580635
Median : 0.915718995332718
Execution Time : 87.611633002758
Rounds : 100
```
As you can see this represents significant improvement with just these changes.  And, except for the fix I put in to the `Socket.close()` method to clear the `isConnected` flag a bit earlier and the removal of a print statement, there were no other significant changes to **BlueSocket**.  You could go even further in the changes to **MongoKitten** changing the data types used to interface better with **BlueSocket** and I'm sure that you'd eventually achieve parity or even better performance than when using the **Vapor**.

Feel free to ask any questions on the changes I made and why I made them.  Thanks for raising this issue, it made for a very interesting day and a couple of good bug fixes and cleanups.  Thanks again.

**Comment by lgaches** [comment]
Thanks @billabt for all your investigations and I'm really sorry for your saturday. I'll check that and try to improve MongoKitten code to handle well BlueSocket.
