### ISSUE TITLE
UDP read operations

### ISSUE THREAD

**Issue by eyerp** [IBM-Swift/BlueSocket#56]
Maybe I'm missing something, but I can't seem to seem to find a safe way to read from a UDP socket.  I'm sending a message and getting a response, but if the server doesnt exist then on read it's locking up.  I didn't see a safe way to check if there is data to be read.  isReadableWriteable() throws an error so I'm assuming that doesn't work with UDP because there is no connection.  

The point it stalls is when it calls Darwin.recvfrom().  Am I missing something?  Should I just ping the server first or is there anything in bluesocket to test that for me?

**Comment by billabt** [comment]
In order to get you this functionality, I need to add two new functions.  The first will set the read timeout and the second will set a receive timeout.  Then you'll be able to set a timeout value prior to executing either a read or write operation.  If the server doesn't respond within the timeout period, the operation will fail with an appropriate error code.  I'll try to get to this over the weekend.  Thanks.

**Comment by eyerp** [comment]
Thank you, I'd much appreciate that.

**Comment by billabt** [comment]
I had some spare cycles this morning.  The APIs have been added along with tests.  Take a look at the `testSetReadTimeout()` test for an example of usage.  The README.md has documentation for the new APIs.  These changes are in the latest version, 0.12.34.

**Comment by eyerp** [comment]
Working perfectly, thanks again.
