### ISSUE TITLE
Inheriting BlueSocket

### ISSUE THREAD

**Issue by TheOkeland** [IBM-Swift/BlueSocket#77]
Is there a reason that the Socket-Class is not open, so that we can use it as a Superclass?

**Comment by billabt** [comment]
Can you give me a use-case for making Socket open?  What would you need to do that would necessitate have to inherit from Socket rather than extend it?  Thanks.

**Comment by TheOkeland** [comment]
In my computer science studies we had the task to write a own TLS-like protocol. In this use case, considering object orientated programming, it is nice to inherit a socket, because you can override existing functions etc. Just extending would not work, because we wanted to provide the same API to the user, for example encrypt incoming data, so we had to override.
This also provided us the possibility that a client or a server was able to handle our sockets just as it would handle normal sockets, not knowing, that the crypto stuff is happening in the background.

**Comment by billabt** [comment]
Take a look at _BlueSSLService_ (https://github.com/IBM-Swift/BlueSSLService).  This does essentially what you want to do using established TLS protocols.  However, instead of inheritance, it uses a _delegation model_.  Take a look at the _protocol SSLServiceDelegate_ in Sources/SocketProtocols.swift.  The hooks for you to provide a TLS-like protocol are already in _Socket_, you just have to take advantage of them.  I think that this would be a more _modern_ approach to doing what you want using _Swift_ rather than inheritance.
