### ISSUE TITLE
setBlocking does not satisfy the connect condition!!

### ISSUE THREAD

**Issue by SelvaBalasubramanian** [IBM-Swift/BlueSocket#79]
If we set the blocking mode to false then the connect should return immediately without any wait but here the connect remains in a waiting state!!

**Comment by billabt** [comment]
I'm looking into this.  I'm seeing the same behavior here...  Been out sick for awhile now but trying to keep things moving along.  Will accept any offers of help.  😉

**Comment by SelvaBalasubramanian** [comment]
Thanks for your respone!!...I to will try it on my side:)

**Comment by billabt** [comment]
I think I've found the problem.  Hope to have a fix posted over the weekend.  I've got the code complete but haven't finished testing.  Will advise...

**Comment by billabt** [comment]
The problem was not with the _setBlocking_ API but with the _connect_ API itself.  _setBlocking_ is working as expected.  I've enhanced the _connect_ API to take a timeout value.  If the value passed is greater than zero, the socket will be placed in non-blocking mode and underlying system connect function will be called.  The API will then wait for the prescribed timeout or a successful connection before returning.

This is now implemented in _version 0.12.60_.
